### PR TITLE
[#4506] fix(UI): Hide jdbc-password value in details page

### LINKED ISSUE #4506: [Bug report] UI: Some password field is still plaintext
### Version

main branch

### Describe what's wrong

image
image

### Error message and/or stacktrace

N/A

### How to reproduce

1. Create a catalog with password field
2. See the password on details pages

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by featherchen**
### What changes were proposed in this pull request?

Hide jdbc-password value in details page.

### Why are the changes needed?

Fix: #4506 

### Does this PR introduce _any_ user-facing change?

Jdbc-password value is not palintext now.

### How was this patch tested?

Screenshot from 2024-08-16 15-31-53
Screenshot from 2024-08-16 15-21-04

### CODE REVIEW

**Comment by LauraXia123** [comment]
@xunliu Would you help to check this?

**Comment by yuqi1129** [comment]
Users can still view the pain as long as they can debug the browser.

**Comment by featherchen** [comment]
> Users can still view the pain as long as they can debug the browser.

@yuqi1129 You are right, I've also mentioned it in #4506, so should we modify the backend api?

**Comment by jerryshao** [comment]
I don't think we need to modify the backend API in this PR, that needs a bunch of work, we can separate into another PR.

**Comment by featherchen** [comment]
> I don't think we need to modify the backend API in this PR, that needs a bunch of work, we can separate into another PR.

Thanks for the advise. I have created an issue (#4571) to track this problem

**Comment by LauraXia123** [comment]
LGTM

**Review by jerryshao — APPROVED** [review]

**Comment by jerryshao** [comment]
@featherchen the auto cherry-pick action is failed for this PR (https://github.com/apache/gravitino/actions/runs/10446609068). Would you please cherry-pick the commit to "branch-0.6" and create a new PR against branch-0.6, thanks a lot.

**Comment by featherchen** [comment]
> @featherchen the auto cherry-pick action is failed for this PR (https://github.com/apache/gravitino/actions/runs/10446609068). Would you please cherry-pick the commit to "branch-0.6" and create a new PR against branch-0.6, thanks a lot.
I have created a PR(#4577) to branch-0.6, please help me review whether I made it in a right way, thanks.

**Comment by eduohe** [comment]
This PR(https://github.com/apache/gravitino/pull/11047) is to fix the password/secrets exposure security issue (https://github.com/apache/gravitino/issues/4571) at the API level

**Pull request merged**
