### PR TITLE
[#4032] Fix(CI): Remove some CI actions to make CI back to normal

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

Remove `csexton/debugger-action@master` action in the github CI, if someone wants this functionality, they can add it in his fork repo and do the debug work the personal account. 

### Why are the changes needed?

This action is not allowed in the Apache project.

Fixed: #4032 

### Does this PR introduce _any_ user-facing change?

N/A.

### How was this patch tested?

Test in the CI

### CODE REVIEW

**Comment by jerryshao** [comment]
Create an issue to track this.

**Comment by jerryshao** [comment]
@yuqi1129 Can you please create an issue to track jacoco issue, I think we can use codecov instead.

**Comment by yuqi1129** [comment]
> @yuqi1129 Can you please create an issue to track jacoco issue, I think we can use codecov instead.

I see.

**Review by jerryshao — APPROVED** [review]
LGTM.

**Pull request merged**
