### PR TITLE
[#4065] improvement(test): Fix the path of integration log is wrong.

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

- Fix the path of the integration test is not as expected. 
- Remove directory data that lies in root project.

### Why are the changes needed?

The path is not right. 

Fixed: #4065 
### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Test locally. 

**Before**

image

**After** 

image

### CODE REVIEW

**Comment by zhoukangcn** [comment]
@yuqi1129 still have this problem with command `./gradlew build -PskipITs -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false -x :clients:client-python:build`
which is used in build.yml

image

**Comment by yuqi1129** [comment]
> @yuqi1129 still have this problem with command `./gradlew build -PskipITs -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false -x :clients:client-python:build` which is used in build.yml
> 
> image

Do you reproduce it in this branch (yuqi1129:minor) or the main branch?

**Comment by zhoukangcn** [comment]
> > @yuqi1129 still have this problem with command `./gradlew build -PskipITs -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false -x :clients:client-python:build` which is used in build.yml
> > image
> 
> Do you reproduce it in this branch (yuqi1129:minor) or the main branch?

on branch yuqi1129:minor

**Comment by yuqi1129** [comment]
> > > @yuqi1129 still have this problem with command `./gradlew build -PskipITs -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false -x :clients:client-python:build` which is used in build.yml
> > > image
> > 
> > 
> > Do you reproduce it in this branch (yuqi1129:minor) or the main branch?
> 
> on branch yuqi1129:minor

Let me check it.

**Comment by yuqi1129** [comment]
> > > > @yuqi1129 still have this problem with command `./gradlew build -PskipITs -PjdkVersion=${{ matrix.java-version }} -PskipDockerTests=false -x :clients:client-python:build` which is used in build.yml
> > > > image
> > > 
> > > 
> > > Do you reproduce it in this branch (yuqi1129:minor) or the main branch?
> > 
> > 
> > on branch yuqi1129:minor
> 
> Let me check it.

It seems that the system property in the log configuration file does not work

image

**Comment by yuqi1129** [comment]
@zhoukangcn 
Could you help to review it again?

**Comment by zhoukangcn** [comment]
> @zhoukangcn Could you help to review it again?

OK，I will check it later

**Comment by zhoukangcn** [comment]
image
@yuqi1129 Does this meet the expectations?

**Comment by zhoukangcn** [comment]
Others LGTM

**Review by zhoukangcn — APPROVED** [review]

**Comment by diqiu50** [comment]
> > image @yuqi1129 Does this meet the expectations?
> 
> @zhoukangcn I think so, @diqiu50 . Can you help to confirm it?

That's fine. It's the Trino container logs

**Comment by yuqi1129** [comment]
> It's the Trino container logs

OK

**Pull request merged**
