### PR TITLE
[#5489] fix(build): Improve the gradle to skip some modules to avoid publishing empty jars

### PR DESCRIPTION
**Pull request by jerryshao**
### What changes were proposed in this pull request?

This PR improves the gradle and release script to skip some modules.

### Why are the changes needed?

This is to avoid some unnecessary empty jars to be published to maven repo.

Fix: #5489 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Tested locally.

### CODE REVIEW

**Review by mchades — COMMENTED** [review]
LGTM. @yuqi1129 Do you want to review it?

**Comment by mchades** [comment]
Does this PR need to be backported to branch-0.7?

**Comment by yuqi1129** [comment]
> LGTM. @yuqi1129 Do you want to review it?

I'm okay with the changes.

**Comment by jerryshao** [comment]
Let me add the label.

**Review by mchades — APPROVED** [review]

**Pull request merged**
