### PR TITLE
[#5573] Add test cases for decimal, array, map, row, format in Trino CI for hive catalog

### PR DESCRIPTION
**Pull request by danhuawang**
### What changes were proposed in this pull request?

1. Add some cases for complex data type
2. Add some cases for different storage format

### Why are the changes needed?

#5573

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

Test locally.

### CODE REVIEW

**Review by diqiu50 — COMMENTED** [review]
It is recommended to use "gt_" as the prefix for schema names, so that residual data can be automatically cleaned up during test startup.

**Comment by danhuawang** [comment]
> It is recommended to use "gt_" as the prefix for schema names, so that residual data can be automatically cleaned up during test startup.

updated

**Comment by jerryshao** [comment]
@danhuawang do you have an issue tracking this PR, if not please create an issue, if so please update the PR title, thanks.

**Comment by danhuawang** [comment]
> @danhuawang do you have an issue tracking this PR, if not please create an issue, if so please update the PR title, thanks.

Done

**Review by diqiu50 — APPROVED** [review]
LGTM

**Pull request merged**
