### PR TITLE
[#5214] Improvement(catalog-lakehouse-paimon): add jdbc-driver to Paimon JDBC catalog backend configuration

### PR DESCRIPTION
**Pull request by caican00**
### What changes were proposed in this pull request?

add jdbc-driver to Paimon JDBC catalog backend configuration

### Why are the changes needed?

Fix: https://github.com/apache/gravitino/issues/5214

### Does this PR introduce _any_ user-facing change?

updated the related doc

### How was this patch tested?
 New IT and modified UT.

### CODE REVIEW

**Comment by FANNG1** [comment]
LGTM, @caican00 could you fix the ci failure?

**Comment by caican00** [comment]
> LGTM, @caican00 could you fix the ci failure?

@FANNG1 fixed.

**Review by FANNG1 — APPROVED** [review]

**Comment by FANNG1** [comment]
@caican00 , I forgot to tag `branch-0.7`, could you propose a new PR based on `branch-0.7` manually?

**Comment by caican00** [comment]
> @caican00 , I forgot to tag `branch-0.7`, could you propose a new PR based on `branch-0.7` manually?

sure

**Comment by caican00** [comment]
> @caican00 , I forgot to tag `branch-0.7`, could you propose a new PR based on `branch-0.7` manually?

@FANNG1 done

**Pull request merged**
