### PR TITLE
[#2625] fix: cannot compile under docker bash

### PR DESCRIPTION
**Pull request by liujinhui1994**
### What changes were proposed in this pull request?

Modified the script to get the version number in grade

### Why are the changes needed?

Compiling under docker bash, the version number cannot be correctly parsed from the gradle file, causing the compilation to fail.

Fix: https://github.com/datastrato/gravitino/issues/2625

### Does this PR introduce _any_ user-facing change?

NO

### How was this patch tested?

Recompile successfully under docker bash

### CODE REVIEW

**Comment by xunliu** [comment]
hi @liujinhui1994 Thank you for your contribution.
Please follow community PR norm, https://github.com/datastrato/gravitino/blob/main/.github/PULL_REQUEST_TEMPLATE
I think you should create an issue

**Comment by liujinhui1994** [comment]
> hi @liujinhui1994 Thank you for your contribution. Please follow community PR norm, https://github.com/datastrato/gravitino/blob/main/.github/PULL_REQUEST_TEMPLATE I think you should create an issue

done

**Comment by jerryshao** [comment]
What is the root cause here, why does this change work, and why it could not be worked previously?

**Comment by liujinhui1994** [comment]
> What is the root cause here, why does this change work, and why it could not be worked previously?

This modification is to obtain the tag number.
It is a string interception operation. The previous code cannot take effect under docker bash, resulting in the failure to obtain the correct version number and compilation failure.

**Comment by jerryshao** [comment]
I think you still don't tell why it cannot be worked in the docker environment, right?

**Pull request closed without merging**
