### PR TITLE
fix(authorization-ranger):the descr field of ranger table x_group is not null

### PR DESCRIPTION
**Pull request by yangyuxia**
### What changes were proposed in this pull request?

When calling the ranger CREATE_GROUP api, the desc field cannot be null

### Why are the changes needed?

When calling the ranger CREATE_GROUP api,  ranger response is error.

### How was this patch tested?

yes, by hand.

### CODE REVIEW

**Comment by xunliu** [comment]
hi @yangyuxia Thank you for your report on this issue.

But Gravitino has integration test the here: https://github.com/apache/gravitino/blob/main/authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java#L715

and I execute this IT, doesn't found any probleam
image

Please tell me, what version Apache Ranger are you using?

**Comment by yangyuxia** [comment]
I test with ranger 2.1.0，found error:
[EL Warning]: 2024-09-19 10:02:23.45--ClientSession(1124729650)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.e
clipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'descr' cannot be null
Error Code: 1048
Call: INSERT INTO x_group (ADDED_BY_ID, CREATE_TIME, CRED_STORE_ID, DESCR, GROUP_SRC, GROUP_TYPE, IS_VISIBLE, GROUP_NAME, OTHER_ATTRIBUTES, STATUS, UPDATE_TI
ME, UPD_BY_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [12 parameters bound]
Query: ValueReadQuery(name="X_GROUP_SEQ" sql="SELECT LAST_INSERT_ID()")

image

**Comment by jerryshao** [comment]
@xunliu can you please review this?

**Review by xunliu — CHANGES_REQUESTED** [review]
Please execute `./gradlew :authorizations:authorization-ranger:spotlessApply` to fix CI failed.

**Comment by jerryshao** [comment]
@yangyuxia would you please fix the conflicts here, we will merge it to 0.6.1 release.

**Comment by yangyuxia** [comment]
fixed

**Review by xunliu — APPROVED** [review]
LGTM

**Pull request merged**
