### PR TITLE
[#5552] feat(core): add metalake pre event to Gravitino event

### PR DESCRIPTION
**Pull request by LiuQhahah**
### What changes were proposed in this pull request?

1. add corresponding MetalakePreEvent 
2. generate pre-event in MetalakeEventDispatcher
3. add test in TestMetalakeEvent
4. add a document in gravitino-server-config.md

### Why are the changes needed?

Fix: #5552

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

(Please test your changes, and provide instructions on how to test it:

UT

### CODE REVIEW

**Comment by orenccl** [comment]
A friendly reminder that your title format is incorrect.
image

**Comment by FANNG1** [comment]
@LiuQhahah is this PR ready to review now?

**Comment by LiuQhahah** [comment]
> @LiuQhahah is this PR ready to review now?

Yes,
Please help to review.
thanks,
Qiang

**Comment by FANNG1** [comment]
@LiuQhahah , Overall LGTM, could you remove unrelated content from the PR description and rebase the PR to resolve the conflict?

**Review by FANNG1 — APPROVED** [review]

**Pull request merged**
