### PR TITLE
[#4190] improvement(jdbc-doris): Remove redundant method call `toString` in log

### PR DESCRIPTION
**Pull request by pravo23**
### What changes were proposed in this pull request?

removed unnecessary call of toString

### Why are the changes needed?

Fix: #4190

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

existing tests

### CODE REVIEW

**Review by jerryshao — APPROVED** [review]
LGTM, thanks for the fix @pravo23

**Comment by jerryshao** [comment]
https://github.com/apache/gravitino/actions/runs/10057590862/job/27799647447?pr=4244 can you please fix the style issue?

**Comment by zhoukangcn** [comment]
> https://github.com/apache/gravitino/actions/runs/10057590862/job/27799647447?pr=4244 can you please fix the style issue?

@pravo23 you can use `./gradlew spotlessApply` to fix the style

**Comment by pravo23** [comment]
Hi, I have fixed the style issue.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
