### PR TITLE
[#5989] The credential type of ADLSTokenCredentialProvider is not equal to the credential type of ADLSTokenCredential 

### PR DESCRIPTION
**Pull request by FANNG1**
### What changes were proposed in this pull request?

 ADLSTokenCredentialProvider use the credential type from ADLSTokenCredential 

### Why are the changes needed?

Fix: #5989 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add test

### CODE REVIEW

**Comment by FANNG1** [comment]
@jerryshao @yuqi1129 @orenccl please help to review when you have time, thanks

**Comment by orenccl** [comment]
What happen when they are not equals?

**Comment by FANNG1** [comment]
> What happen when they are not equals?

Gravitino server support credential vending too, if not equal, the server side creates a credential with type A. On the client side, it couldn't deserialize the credential, because the service loader uses the credential type like B from credential.

**Comment by FANNG1** [comment]
> What happen when they are not equals?

no bad effect, but we'd better keep it consistent to make the system simple

**Review by orenccl — APPROVED** [review]
Got it! LGTM

**Comment by tengqm** [comment]
LGTM.

**Comment by FANNG1** [comment]
updating the PR to replace `adls-sas-token` with `adls-token` for the credential type of `ADLSTokenCredential` to keep with other credential types like `s3-token`, `oss-token`, `gcs-token`, please help to review again

**Review by orenccl — APPROVED** [review]
LGTM. Thank you for fixing naming.

**Comment by tengqm** [comment]
Nice cleanup.

**Comment by jerryshao** [comment]
@FANNG1 can you please rebase the PR to fix the conflicts?

**Comment by FANNG1** [comment]
> @FANNG1 can you please rebase the PR to fix the conflicts?

updated

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
