### PR TITLE
[#3185] fix(doc): Use the iceberg latest version url in doc

### PR DESCRIPTION
**Pull request by lw-yang**
### What changes were proposed in this pull request?

we found the `https://iceberg.apache.org/docs/1.3.1/configuration/` url doesn't work, we shoud use the latest version url to avoid this

### Why are the changes needed?

Fix: #3185 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by qqqttt123** [comment]
One point:
It should be consistent with the version which our project used.

**Comment by jerryshao** [comment]
Do we support newest version of Iceberg @FANNG1 , if not, we'd better not change the document until we support it.

**Comment by FANNG1** [comment]
> Do we support newest version of Iceberg @FANNG1 , if not, we'd better not change the document until we support it.

we support Iceberg 1.3.1 for now, but the 1.3.1 configuration doc is not exists for now.

**Comment by jerryshao** [comment]
So, we'd better add newer version support before updating the docs.

**Comment by FANNG1** [comment]
@lw-yang Iceberg in Gravitino is updated to `1.5.2`, could you update the PR?

**Review by FANNG1 — APPROVED** [review]

**Comment by FANNG1** [comment]
@lw-yang , merged to main, thanks for your contribution!

**Pull request merged**
