### PR TITLE
[#4661] improvement(iceberg-rest): Adding License and Notice to the i…

### PR DESCRIPTION
**Pull request by yaoderek**
### What changes were proposed in this pull request?

Adding license and notice to iceberg-rest-server and gravitino server jars

### Why are the changes needed?

Fix: #4661 The release jar should contains LICENSE and NOTICE

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Build results attached.
licensenotice

### CODE REVIEW

**Comment by yaoderek** [comment]
@justinmclean can you help review this PR? Thanks!

**Comment by justinmclean** [comment]
The iceberg LICENSE and NOTICE files are probably going to be different from the root gravitino one as the release artifact produced will have different contents, but this is obviously an improvement.

**Comment by yaoderek** [comment]
Thanks @justinmclean for the feedback. Change to download LICENSE/NOTICE from iceberg repo and put them under META-INF.

**Comment by justinmclean** [comment]
This is not quite right. The content of our LICENSE and NOTICE file would not be the same as the contents for the Apache Iceberg project; it will depend on what ends up in the release artifact. I can take a look and see what those contents should be if you want.

**Comment by yaoderek** [comment]
sure, please do. Thanks @justinmclean. I reverted the last two commits.

**Comment by justinmclean** [comment]
See #5011 for the LICENSE and NOTICE files

**Comment by yaoderek** [comment]
> See #5011 for the LICENSE and NOTICE files

Nice, thanks @justinmclean for sharing and help. I will close this PR.

**Pull request closed without merging**
