### PR TITLE
[#4154] improvment(client): Move access control function to GravitinoClient

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?

 Move access control function to GravitinoClient

### Why are the changes needed?

Fix: #4154

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
Modified the UTs.

### CODE REVIEW

**Comment by jerryshao** [comment]
I'm OK with the changes, @yuqi1129 can you please take another look, thanks.

**Comment by FANNG1** [comment]
why moving access control function from `GravitinoAdminClient` to `GravitinoClient`?

**Comment by jerqi** [comment]
> why moving access control function from `GravitinoAdminClient` to `GravitinoClient`?

Access control operations can be executed by normal users instead of admins.

**Comment by FANNG1** [comment]
> > why moving access control function from `GravitinoAdminClient` to `GravitinoClient`?
> 
> Access control operations can be executed by normal users instead of admins.

IMO, it should be executed by admins not users, could you describe the reason?

**Comment by jerqi** [comment]
> > > why moving access control function from `GravitinoAdminClient` to `GravitinoClient`?
> > 
> > 
> > Access control operations can be executed by normal users instead of admins.
> 
> IMO, it should be executed by admins not users, could you describe the reason?

If every user have the privilege, they should have ability the execute the action. They shouldn't bind to the role of admin. Admin only creates the metalake. The rest operaions should be executed by normal users.

**Review by xunliu — APPROVED** [review]
LGTM
If no more comments, I will merge this PR.

**Comment by jerqi** [comment]
> LGTM If no more comments, I will merge this PR.

wait for a moment.

**Comment by jerqi** [comment]
> > LGTM If no more comments, I will merge this PR.
> 
> wait for a moment. I will make a minor fix.

Done.

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
