### PR TITLE
[#4785] improvement(docs): Remove the copy right `datastrato` in the picture.

### PR DESCRIPTION
**Pull request by yuqi1129**
### What changes were proposed in this pull request?

Remove any improper copyright data after the project has been donated to Apache

### Why are the changes needed?

Better user experience.

Fix: #4785 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by jerryshao** [comment]
So the license information is already remove in the web UI?

**Comment by yuqi1129** [comment]
> So the license information is already remove in the web UI?

Yeah, this is the picture:
image

**Review by jerryshao — APPROVED** [review]
LGTM.

**Comment by jerryshao** [comment]
Is this the issue you're tracking https://github.com/apache/gravitino/issues/4785?

**Comment by yuqi1129** [comment]
> Is this the issue you're tracking #4785?

Yeah.

**Comment by justinmclean** [comment]
"Copyright 2023 Gravitino" is not strictly correct. The project as a whole is copyrighted by Apache Software Foundation, but individual pieces are copyrighted by the person (or in most cases the company they work for) who created them. I would change the text in the web UI to be "© 2024 ASF" or "© 2024 Apache Software Foundation".

**Comment by yuqi1129** [comment]
@justinmclean 
I see, thanks.

**Pull request merged**
