### PR TITLE
[#5683] Improvement: Remove gravitino-web-*.jar from Gravitino release files

### LINKED ISSUE #5683: [Improvement] Remove `gravitino-web` jar from release package
### What would you like to be improved?

After execute `./gradlew compileDistribution -x test -x :docs:lintOpenAPI`, some unexpected jars like `gravitino-web-xxx.jar` in the release package.

image
 

This a mirror issue of https://github.com/apache/gravitino/issues/5490, please refer to it to solve the problem

### How should we improve?

_No response_

### PR DESCRIPTION
**Pull request by TungYuChiang**
### Why are the changes needed?

close #5683 

### Does this PR introduce _any_ user-facing change?

None

### How was this patch tested?

Using following command
`./gradlew compileDistribution -x test -x :docs:lintOpenAPI`

### CODE REVIEW

**Comment by tengqm** [comment]
lgtm

**Comment by jerryshao** [comment]
@TungYuChiang can you please change the PR title to follow the format like other PRs?

**Comment by TungYuChiang** [comment]
@jerryshao Thank you for the reminder, I have made the change.

**Comment by TungYuChiang** [comment]
This issue works fine on my local environment. The changes I pushed are based on the logic from the other issue #5490 , and I have ensured that web JAR packages are not included.

**Comment by yuqi1129** [comment]
> This issue works fine on my local environment. The changes I pushed are based on the logic from the other issue #5490 , and I have ensured that web JAR packages are not included. @yuqi1129

I have repeatedly verified this issue and it occurs if we develop the project from version 0.6.0 to 0.8.0, in the latest main branch, this problem does not exist. 

@TungYuChiang Thanks for your hard work. I'll remove it as it's not a problem.

**Pull request closed without merging**
