### PR TITLE
#5440 fix(web): include missing JDBC properties in catalog creation payload for Apache Iceberg

### PR DESCRIPTION
**Pull request by niyushabaghayi**
Why are the changes needed?
These changes are needed to address a bug in the Gravitino UI that prevents users from successfully creating a catalog with `type: relational` and `provider: Apache Iceberg`. The missing properties cause a 400 error on the backend, blocking catalog creation.

Fix: #5440 

Does this PR introduce any user-facing change?
Yes, this PR allows users to create catalogs with `type: relational` and `provider: Apache Iceberg` without encountering a 400 error due to missing JDBC properties. It resolves the issue of incomplete payloads and improves catalog creation reliability.

How was this patch tested?
1. Manual Testing:
  - Opened the "Create Catalog" dialog in the Gravitino UI.
  - Set `type` to `relational`, `provider` to `Apache Iceberg`, and configured `catalog-backend` as `jdbc` with appropriate `jdbc-driver`, `jdbc-user`, and `jdbc-password` values.
  - Clicked "Create" and verified successful catalog creation without errors.

2. Steps to Test:
Follow the reproduction steps outlined in the issue report to confirm that the changes address the problem.

3. Edge Cases:
Tested with `catalog-backend` set to `jdbc` and verified correct behavior.

### CODE REVIEW

**Comment by jerryshao** [comment]
@LauraXia123 would you please help to review this PR?

**Comment by LauraXia123** [comment]
@niyushabaghayi hi, the latest commit have no issue about #5440 , let me know if you have any problems after retesting!

**Comment by niyushabaghayi** [comment]
Thanks, @LauraXia123! Could you please point me to the specific issue and related PR that resolved this problem? I tried searching but couldn't find it, and I'm still experiencing the issue on the latest version (Gravitino 0.6.1-incubating). Any guidance would be greatly appreciated!

**Comment by LauraXia123** [comment]
Fixed on (Gravitino 0.7.0-incubating), you can retry it on main branch or tag (v0.7.0-incubating-rc2).

**Pull request closed without merging**
