### PR TITLE
[#4772][#4766] improve(pydoc): Remove compile path in the python client docs

### PR DESCRIPTION
**Pull request by xunliu**
### What changes were proposed in this pull request?

Remove compile path in the python client docs.

#### Before
image

#### After
image

Fix: #4772
Fix: #4766 

### Does this PR introduce _any_ user-facing change?

N/A

### How was this patch tested?

CI passed.

### CODE REVIEW

**Comment by noidname01** [comment]
LGTM

**Review by noidname01 — APPROVED** [review]

**Comment by jerryshao** [comment]
Looks like we still have the issue about the local path here, please look at my screenshot. Not sure how other projects generate the python doc, maybe they use different tools. If we cannot fix this problem, I would suggest we don't publish the python doc in this release, until we have a better solution. What do you think @xunliu @noidname01 @diqiu50 ?

image

**Comment by noidname01** [comment]
@jerryshao I think so, the other big Python projects like PyTorch seem to use [Sphinx](https://www.sphinx-doc.org/en/master/), but it requires additional configuration in code and docstrings, so I think it's better to do it in next release.

**Comment by xunliu** [comment]
@noidname01 Yes, I agree with your suggestion.
So, I create issue #4797 to track this problem.

**Comment by jerryshao** [comment]
@xunliu can you please close this PR, seems not required anymore.

**Pull request closed without merging**
