### PR TITLE
[MINOR] community: Add roryqi and diqiu to collaborators

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request?
My another github account is @qqqttt123 .  

I and @diqiu50 have contributed for a period time for the Gravitino community.
We want to contribute more. So I want to add us to the collaborators.

About collaborators, you can see https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features

### Why are the changes needed?
Just a minor.

### Does this PR introduce _any_ user-facing change?
No.

### How was this patch tested?
No.

### CODE REVIEW

**Comment by jerqi** [comment]
@jerryshao @yuqi1129 @xunliu @mchades

**Comment by justinmclean** [comment]
The project has not discussed adding collaborators in this way. This would first need to be first agreed to by the PPMC on the project's mailing list.

**Comment by jerryshao** [comment]
Yes, this should be discussed in private mail list firstly.

**Comment by jerqi** [comment]
OK, I close this pull request first.

**Pull request closed without merging**
