### PR TITLE
Show gravitino logo in IDEA

### PR DESCRIPTION
**Pull request by totalo**
QQ_1722326663092

### CODE REVIEW

**Comment by yuqi1129** [comment]
@totalo 
Please modify the PR description as others have done.

**Comment by jerryshao** [comment]
@totalo thanks a lot for your contribution, can you please create a related issue for this, also please update the PR title and description to follow this project's rule? Thanks a lot.

**Comment by totalo** [comment]
> @totalo Please modify the PR description and title as others have done.

Ok.

**Comment by totalo** [comment]
> @totalo thanks a lot for your contribution, can you please create a related issue for this, also please update the PR title and description to follow this project's rule? Thanks a lot.

ok.

**Pull request closed without merging**
