### PR TITLE
[#4135] fix(trino-connector):  Fix typo about Gravitino in trino-connector

### PR DESCRIPTION
**Pull request by Dev79844**
### Why are the changes needed?
Fix: #4135

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Existing UTs

### CODE REVIEW

**Review by diqiu50 — APPROVED** [review]

**Review by diqiu50 — APPROVED** [review]
LGTM

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by yuqi1129** [comment]
@Dev79844 
Please make changes to the PR title and description as that of other PRs.

**Comment by Dev79844** [comment]
@yuqi1129
I have updated the title and description of PR.

**Pull request merged**
