### PR TITLE
[#5318][#5311][#5328] improvement(web): Add jdbc-driver properties for Paimon JDBC and fix jdbc issue

### PR DESCRIPTION
**Pull request by LauraXia123**
### What changes were proposed in this pull request?
1. Add jdbc-driver properties for Paimon JDBC
image

3. fix update paimon catalog issue

### Why are the changes needed?
N/A

Fix: #5318
Fix: #5311
Fix: #5328

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
manually

### CODE REVIEW

**Comment by jerryshao** [comment]
@LauraXia123 can you please fix the PR title?

**Comment by jerryshao** [comment]
@FANNG1 please help to review it.

**Comment by FANNG1** [comment]
@LauraXia123 could you post a picture to show the paimon jdbc-driver property?

**Comment by LauraXia123** [comment]
> @LauraXia123 could you post a picture to show the paimon jdbc-driver property?

updated

**Review by FANNG1 — DISMISSED** [review]

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
