### PR TITLE
feat(oceanbase-jdbc-catalog)：Add full code to support non-partitioned tables for OceanBase-CE JDBC catalog

### PR DESCRIPTION
**Pull request by yuanoOo**
### What changes were proposed in this pull request?

- add catalog-jdbc-oceanbase module
- add full code to support non-partitioned tables

### Why are the changes needed?

Fix: #4906 

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?

Unit tests have been added, integration tests will be added later.

### CODE REVIEW

**Comment by yuanoOo** [comment]
@mchades Please take a look in your free time.

**Comment by mchades** [comment]
Could you please submit a code skeleton without the implementations? The PR is too large to review.

**Comment by yuanoOo** [comment]
> Could you please submit a code skeleton without the implementations? The PR is too large to review.

OK, I'll try.

**Comment by mchades** [comment]
done by #5228

**Pull request closed without merging**
