### PR TITLE
[#5700] feat(CLI):Add extended help for catalogs in Gravitino CLI

### PR DESCRIPTION
**Pull request by chenyuan99**
### What changes were proposed in this pull request?

Added extended help for catalog commands.

### Why are the changes needed?

To provide user with extra help.

Fix: #5700

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

N/A

### CODE REVIEW

**Comment by chenyuan99** [comment]
@justinmclean this is ready to review

**Comment by justinmclean** [comment]
The change looks good to me, except the rat exclusion path is incorrect.

**Comment by chenyuan99** [comment]
fixed the path issue, Thanks for the heads up!

**Comment by jerryshao** [comment]
Looks like this file misses the license header, I'm curious why it can still pass the CI?

**Comment by jerryshao** [comment]
OK, I see.

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
