### PR TITLE
[#4530] improvement(kafka-catalog): reduce kafka catalog libs size from 91MB to 17MB

### PR DESCRIPTION
**Pull request by mchades**
### What changes were proposed in this pull request?

remove some unnecessary dependencies

### Why are the changes needed?

Fix: #4530 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

CI passed

### CODE REVIEW

**Comment by jerryshao** [comment]
Can you please list all the jars after you excluded, @mchades ?

**Comment by mchades** [comment]
@jerryshao FYI
before:
image
image

after:
image

**Comment by jerryshao** [comment]
Do we need to exclude runtime guava and slf4j jars like @yuqi1129 did for jdbc catalog? I think our base classloader already provided these jars.

**Comment by mchades** [comment]
> Do we need to exclude runtime guava and slf4j jars like @yuqi1129 did for jdbc catalog? I think our base classloader already provided these jars.

fixed

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
