### PR TITLE
[#5168][#5169][#5170] Feature(web): Add ui support for creating, editing, viewing, and deleting fileset

### PR DESCRIPTION
**Pull request by LauraXia123**
### What changes were proposed in this pull request?
Add ui support for creating, editing, viewing, and deleting fileset
image

### Why are the changes needed?
N/A

Fix: #5168
Fix: #5169
Fix: #5170

### Does this PR introduce _any_ user-facing change?
N/A

### How was this patch tested?
manually

### CODE REVIEW

**Comment by yuqi1129** [comment]
The overall function is okay.
image


except there is an unexpected button `create schema` on the fileset page.
image

**Comment by LauraXia123** [comment]
image

**Comment by jerryshao** [comment]
@LauraXia123 the issue id you linked is not existed, can you please change to the correct issue numbers?

**Comment by yuqi1129** [comment]
I have verified it again, and no problem has been found again.

**Comment by LauraXia123** [comment]
> @LauraXia123 the issue id you linked is not existed, can you please change to the correct issue numbers?

fixed

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
