### PR TITLE
[#5551] feat(core): add topic pre-event to Gravitino event.

### PR DESCRIPTION
**Pull request by LindaSummer**
### What changes were proposed in this pull request?

Add pre-events for topic events, including `AlterTopicPreEvent`, `CreateTopicPreEvent`, `DropTopicPreEvent`, `ListTopicPreEvent` and `LoadTopicPreEvent`.

### Why are the changes needed?

Fix: #5551 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Related Unit Tests have been added.

### CODE REVIEW

**Review by FANNG1 — DISMISSED** [review]

**Comment by FANNG1** [comment]
@LindaSummer ,  could you add LICENSE header to xxEvent to fix rat check error?

**Comment by jerryshao** [comment]
Can you please fix the license header issue for your newly added files?

**Comment by LindaSummer** [comment]
Hi @FANNG1 , @jerryshao ,

Of course, I will add license headers today.😄

Best Regards,
Edward

**Comment by LindaSummer** [comment]
> hi @LindaSummer Thank you for your contribution! I was trying to contact you, This is my email [liuxun@apache.org](mailto:liuxun@apache.org), Please send an email to me, Thank you :-)

Hi @xunliu ,

  I'm very happy to have the chance to get in touch.  😊
  I have sent a greeting email to you.

Best Regards,
Edward

**Review by FANNG1 — APPROVED** [review]

**Comment by FANNG1** [comment]
@LindaSummer , merged to main, thanks for your contribution!

**Pull request merged**
