### PR TITLE
[#3871] Improvement(spark-connector): Making Iceberg extended sqls compatible with different iceberg versions

### PR DESCRIPTION
**Pull request by caican00**
### What changes were proposed in this pull request?

compatible with different iceberg versions by reflection.

### Why are the changes needed?

Making Iceberg extended sqls compatible with different iceberg versions.
For example, in some lower version, such as `0.14.x`, `CreateOrReplaceBranch` is not available.

Fix: https://github.com/datastrato/gravitino/issues/3871

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

existing ITs.

### CODE REVIEW

**Comment by FANNG1** [comment]
`0.14.x` is an older version, I'm not sure whether to support it, especially with some reflection methods. cc @jerryshao

**Comment by caican00** [comment]
> `0.14.x` is an older version, I'm not sure whether to support it, especially with some reflection methods. cc @jerryshao

`1.3.x `is also slightly different from `1.4.x`.
image

added the `create` parameter in `1.4.x`
image

Same for `createOrReplaceTag`

**Comment by jerryshao** [comment]
We should define some supported versions, we should not extend to support too many version, that will increase our support burden.

**Comment by justinmclean** [comment]
This may help:
https://iceberg.apache.org/multi-engine-support

**Pull request closed without merging**
