### PR TITLE
[#5520] improvement(JDBC-connection): handle JDBC access denied exception

### PR DESCRIPTION
**Pull request by mchades**
### What changes were proposed in this pull request?

catch JDBC access denied exception and convert to UnauthorizedException

### Why are the changes needed?

The REST client need the real exception instead of GravitinoRuntimeException

Fix: #5520 

### Does this PR introduce _any_ user-facing change?

no

### How was this patch tested?

ITs added

### CODE REVIEW

**Comment by jerqi** [comment]
Why is this unauthorized code? This should be used by server authorization instead of external system's authorization. It should be illegalArgumentException.

**Comment by jerryshao** [comment]
Is it ready for review?

**Review by jerryshao — DISMISSED** [review]

**Comment by jerryshao** [comment]
@yuqi1129 can you please also take a look?

**Comment by jerryshao** [comment]
@yuqi1129 @jerqi please help to review again.

**Comment by mchades** [comment]
Gently ping @yuqi1129 @jerqi

**Review by yuqi1129 — APPROVED** [review]
I have checked, it looks good to me.

**Review by jerqi — APPROVED** [review]

**Pull request merged**
