### PR TITLE
[#4460] feat(core): Add the method call of the authorizationPlugin 

### PR DESCRIPTION
**Pull request by jerqi**
### What changes were proposed in this pull request? 
If we want to push the privileges down the underlying system, we need to call methods of the underlying system authorization plugin.

### Why are the changes needed?

Fix: #4460

### Does this PR introduce _any_ user-facing change? 

No.

### How was this patch tested?
Add some test cases.

### CODE REVIEW

**Comment by jerryshao** [comment]
Is this a backport PR?

**Comment by jerryshao** [comment]
@yuqi1129 please merge it when CI is passed.

**Comment by yuqi1129** [comment]
The backend test with condition JDBK17, embedded and MySQL failed as a result of the timeout. I tried again. There is a chance that the test will hang.

**Comment by jerqi** [comment]
> The backend test with condition JDBK17, embedded and MySQL failed as a result of the timeout. I tried again. There is a chance that the test will hang.

Let us merge it.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
