### PR TITLE
[#5568] Update help content for Gravitino CLI

### PR DESCRIPTION
**Pull request by justinmclean**
### What changes were proposed in this pull request?

Update help content and fix a few minor issues in the documentation

### Why are the changes needed?

To provide more help to users.

Fix: #5568

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Tested locally.

### CODE REVIEW

**Comment by shaofengshi** [comment]
The content in these "_help.txt" files are duplicated to some extend with the "cli.md" file. Is it possible to combine them so that easier for maintain? For example, fetch some lines from the md file to the output, or print the documentation URL to console, asking the user to check.

@jerryshao @xunliu what's your opinion?

**Comment by justinmclean** [comment]
It is not so easy to use the the same content as a) the formats (including whitespace) are different b) in some cases multiple parts are used in a single help file.

**Comment by shaofengshi** [comment]
> It is not so easy to use the the same content as a) the formats (including whitespace) are different b) in some cases multiple parts are used in a single help file.

I agree; how about print the URL of the document (on Gravitino website or github)? Just want to make it simple, so that we don't need maintain multi-places.

**Comment by justinmclean** [comment]
We need to provide the user with help and example commands in teh commands help. See https://clig.dev/#help

**Comment by justinmclean** [comment]
If we want to remove the duplication, it may be best to remove the examples from the CLI.md file?

**Review by shaofengshi — APPROVED** [review]
LGTM

**Comment by shaofengshi** [comment]
> We need to provide the user with help and example commands in the commands help. See https://clig.dev/#help

get it, make sense.

**Comment by shaofengshi** [comment]
> If we want to remove the duplication, it may be best to remove the examples from the CLI.md file?

we can think about it later, after getting some user feedbacks.

**Pull request merged**
