### PR TITLE
[#4606] Improvement(trino-connector): Possible null pointer expection/code handling

### PR DESCRIPTION
**Pull request by jingjia88**
### What changes were proposed in this pull request?

- Remove the outer try block and throw new TrinoException exception by passing failedException.
- The InterruptedException during Thread.sleep is handled.

### Why are the changes needed?

Fix: #4606 

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

use original UT

### CODE REVIEW

**Comment by justinmclean** [comment]
Thanks @jingjia88 for your contribution. I like that you are handling the thread correctly, but I think this could be simplified further. @jerryshao what do you think?

**Comment by jingjia88** [comment]
@justinmclean How about changing the initial `null` to a default exception  ?

**Comment by jerryshao** [comment]
@diqiu50 can you please help to review this?

**Review by diqiu50 — APPROVED** [review]
LGTM

**Review by jerryshao — APPROVED** [review]

**Pull request merged**
