### PR TITLE
[hotfix] Fix irregular variable names

### PR DESCRIPTION
**Pull request by zhuangchong**
### What changes were proposed in this pull request?

Fix irregular variable names: tablename -> tableName

### Why are the changes needed?

Variable name `tablename` is irregular

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Modify variable name naming convention, no testing required.

### CODE REVIEW

**Comment by yuqi1129** [comment]
@zhuangchong 
Thank you for your help. Please modify the PR description.
image

If you encounter any problems, please refer to the descriptions of other PRs.

**Comment by zhuangchong** [comment]
> @zhuangchong Thank you for your help. Please modify the PR description. image
> 
> If you encounter any problems, please refer to the descriptions of other PRs.

done.

**Comment by yuqi1129** [comment]
@zhuangchong 
Can you correct all the typos `tablename` in the project?

**Comment by zhuangchong** [comment]
> @zhuangchong Can you correct all the typos `tablename` in the project?

The existing "tablename" is in the test class and makes sense. So there is no longer an irregularly named variable `tablename`.

**Comment by yuqi1129** [comment]
> > @zhuangchong Can you correct all the typos `tablename` in the project?
> 
> @yuqi1129 The existing `tablename` is in the test class and makes sense. So there is no longer an irregularly named variable `tablename`.

Okay

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Comment by yuqi1129** [comment]
@zhuangchong 
Thank you for your contributions.

**Pull request merged**
