### PR TITLE
[#5968] fix(server-common): The owner of the catalog is incorrect when using Basic Auth and Password is empty

### PR DESCRIPTION
**Pull request by frankvicky**
### Why are the changes needed?
Current implementation of `SimpleAuthenticator` doesn't comply with HTTP Basic Authentication specification, which allows username-only or username with empty password formats.

Fix: #5968 

### Does this PR introduce _any_ user-facing change?
n/a
### How was this patch tested?
Unit test

### CODE REVIEW

**Comment by frankvicky** [comment]
Hi @jerqi 
Could you please take a look ?
Many thanks

**Comment by jerqi** [comment]
Could you add more cases?
like`user1:`,`:password`?

**Review by jerqi — APPROVED** [review]
LGTM.

**Review by xunliu — APPROVED** [review]
@frankvicky Thank you for your contributions.
LGTM

**Pull request merged**
