### PR TITLE
[#3731] docs(API): Update the tutorial and document for the Java client API change

### PR DESCRIPTION
**Pull request by shaofengshi**
### What changes were proposed in this pull request?

Update the documentations for the latest Java API change

### Why are the changes needed?

To make the document sync with API change.

Fix: #3731

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Document, local previewd.

### CODE REVIEW

**Comment by yuqi1129** [comment]
@shaofengshi 
Can you also modify the Java doc regarding interface changes? for example 

```java
  /**
   * Create a fileset metadata in the catalog.
   *
   * <p>If the type of the fileset object is "MANAGED", the underlying storageLocation can be null,
   * and Gravitino will manage the storage location based on the location of the schema.
   *
   * <p>If the type of the fileset object is "EXTERNAL", the underlying storageLocation must be set.
   *
   * @param ident A fileset identifier.
   * @param comment The comment of the fileset.
   * @param type The type of the fileset.
   * @param storageLocation The storage location of the fileset.
   * @param properties The properties of the fileset.
   * @return The created fileset metadata
   * @throws NoSuchSchemaException If the schema does not exist.
   * @throws FilesetAlreadyExistsException If the fileset already exists.
   */
  Fileset createFileset(
      NameIdentifier ident,
      String comment,
      Fileset.Type type,
      String storageLocation,
      Map<String, String> properties)
      throws NoSuchSchemaException, FilesetAlreadyExistsException;
```

The `ident` in method `createFileset` is different from before(before: {metalakeName}.{catalogName}.{schemaName}.{filesetName}, after:{schemaName}.{filesetName}) , the sentence "A fileset identifier" is very vague.

**Comment by shaofengshi** [comment]
> @shaofengshi Can you also modify the Java doc regarding interface changes? for example
> 
> ```java
>   /**
>    * Create a fileset metadata in the catalog.
>    *
>    * <p>If the type of the fileset object is "MANAGED", the underlying storageLocation can be null,
>    * and Gravitino will manage the storage location based on the location of the schema.
>    *
>    * <p>If the type of the fileset object is "EXTERNAL", the underlying storageLocation must be set.
>    *
>    * @param ident A fileset identifier.
>    * @param comment The comment of the fileset.
>    * @param type The type of the fileset.
>    * @param storageLocation The storage location of the fileset.
>    * @param properties The properties of the fileset.
>    * @return The created fileset metadata
>    * @throws NoSuchSchemaException If the schema does not exist.
>    * @throws FilesetAlreadyExistsException If the fileset already exists.
>    */
>   Fileset createFileset(
>       NameIdentifier ident,
>       String comment,
>       Fileset.Type type,
>       String storageLocation,
>       Map<String, String> properties)
>       throws NoSuchSchemaException, FilesetAlreadyExistsException;
> ```
> 
> The `ident` in method `createFileset` is different from before(before: {metalakeName}.{catalogName}.{schemaName}.{filesetName}, after:{schemaName}.{filesetName}) , the sentence "A fileset identifier" is very vague.

ok, I can update the java docs together in this PR

**Comment by shaofengshi** [comment]
> @shaofengshi Can you also modify the Java doc regarding interface changes? for example
> 
> ```java
>   /**
>    * Create a fileset metadata in the catalog.
>    *
>    * <p>If the type of the fileset object is "MANAGED", the underlying storageLocation can be null,
>    * and Gravitino will manage the storage location based on the location of the schema.
>    *
>    * <p>If the type of the fileset object is "EXTERNAL", the underlying storageLocation must be set.
>    *
>    * @param ident A fileset identifier.
>    * @param comment The comment of the fileset.
>    * @param type The type of the fileset.
>    * @param storageLocation The storage location of the fileset.
>    * @param properties The properties of the fileset.
>    * @return The created fileset metadata
>    * @throws NoSuchSchemaException If the schema does not exist.
>    * @throws FilesetAlreadyExistsException If the fileset already exists.
>    */
>   Fileset createFileset(
>       NameIdentifier ident,
>       String comment,
>       Fileset.Type type,
>       String storageLocation,
>       Map<String, String> properties)
>       throws NoSuchSchemaException, FilesetAlreadyExistsException;
> ```
> 
> The `ident` in method `createFileset` is different from before(before: {metalakeName}.{catalogName}.{schemaName}.{filesetName}, after:{schemaName}.{filesetName}) , the sentence "A fileset identifier" is very vague.

done, please review again, thanks!

**Comment by yuqi1129** [comment]
It's okay with me.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
