### PR TITLE
[#4817] fix(core): Fix unexpected tag delete issue

### PR DESCRIPTION
**Pull request by jerryshao**
### What changes were proposed in this pull request?

This PR fixes the tag relation unexpected deletion issue. Previously we deleted other unrelated tag relations under the metalake, which will make the associated tag list fail. So this PR will fix this issue.

### Why are the changes needed?

To fix the tag unexpectedly deleted issue.

Fix: #4817 

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Add new IT to fix this issue.

### CODE REVIEW

**Comment by jerryshao** [comment]
@yuqi1129 @mchades please help me to review this bug fix, thanks.

**Comment by yuqi1129** [comment]
Please resolve the conflict here.

**Comment by jerryshao** [comment]
@yuqi1129 @mchades please help to review again.

**Review by yuqi1129 — APPROVED** [review]
LGTM

**Pull request merged**
